### ISSUE TITLE
Mapping Guide notes

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/r-at-urban#51]
- [x] Add flow. 
- [x] remove Kyle
- [x] Fix-width font for code
- [x] Turn video into link
- [x] Give credit to XKCD
- [x] Look at Globe image copyright'Replace `T` with `TRUE` 
- [x] Replace `=` with `<-`
- [x] Check ESRI:102003 vs. EPSG:5070
- [x] Add `library(crsuggest)` example
- [x] Say OpenStreetMap are for exploratory only
- [x] Add points, lines, and polygons
- [x] Consolidate some examples--all examples should model best practices
- [x] Fix layering section with `shift_geometry()`
- [x] `scale_fill_gradientn()` for fill. 
- [x] Format bins with correct dashes. 
- [x] Switch tab to geospatial.

1. Get Spatial Data
2. Project Spatial Data
3. Map
4. Analysis
5. Modeling

**Comment by ajjitn** [comment]
Closed with 5535726e7a043defb2be212777bad0daf5c574d7
